name: Preview Docs

on:
  pull_request_target:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: preview-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docs
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
      - name: Installation
        run: yarn

      - name: Check translations pages consistency
        run: python3 ./scripts/check_i18n_consistency.py

      - name: Build docs
        run: yarn build

      - name: Archive the docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/

  deploy:
    name: Deploy GitHub Pages preview
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment preview link on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          comment-tag: gh-pages-preview
          mode: recreate
          message: |
            ✅ Preview deployed!  
            🌍 [Click here to view the documentation preview](${{ steps.deployment.outputs.page_url }})
