name: Preview Docs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: preview-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Check translation consistency
        run: python3 ./scripts/check_i18n_consistency.py

      - name: Build the docs
        run: |
          echo "Using baseUrl=$BASE_URL"
          yarn build
        env:
          BASE_URL: /preview-${{ github.event.pull_request.number }}/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    name: Deploy preview to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview
      
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Comment PR with preview link
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          comment-tag: gh-pages-preview
          mode: recreate
          message: |
            ✅ Preview deployed for this PR!  
            🌍 [View the documentation preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview-${{ github.event.pull_request.number }}/)
